---
- name: instance profile iam roles
  hosts: localhost
  gather_facts: false
  tasks:
    - name: creating instance profile
      amazon.aws.iam_instance_profile:
        access_key: AKIAROBAFHXCJESEPDAY
        secret_key: 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
        name: viki-another
        role: viki-s3read-o
        path: /org/comp/here/
        state: present
    - name: now delete the instance profile
      amazon.aws.iam_instance_profile:
        access_key: AKIAROBAFHXCJESEPDAY
        secret_key: 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
        name: viki-another
        state: absent
        
