---
- name: starting an instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: starting a windows22 instance
    amazon.aws.ec2_instance:
      state: running
      instance_ids: "i-090cfb6055d6e0999"
